spring.application.name=libreria
# Configuarcion de conexion
spring.datasource.url="jdb.mysql://localhost:3306/dblibreriacarrito?useSSL=false&serverTimezone=UTC"
spring.datasource.username="root"
spring.datasource.password="root"

# Dialecto de MySQL
# spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

# Esquema
spring.jpa.hibernate.ddl-auto="update"

# Mostrar en consola
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Driver
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

